library(Seurat)

## read in the final annotated ge_So object
ge_so <- readRDS('/data1/APA/Paul_ALS_Data/ALS_snRNA_final.RDS')
ge_so <- subset(ge_so, subset=chemistry=='V3')
## filter the V3
ge_so <- SetIdent(ge_so, value = ge_so$Velm_cellsubtype)


exp_profiles <- AverageExpression(ge_so)
dim(exp_profiles[['SCT']])
write.table(exp_profiles[['SCT']], '/home/aiden/codes/APA_stuff/post_qual/APA/For_DL_model/celltype_profiles.tsv', sep='\t',
          quote=F)

table(ge_so$celltype)
table(ge_so$Velm_cellsubtype)

ge_so <- SetIdent(ge_so, value = ge_so$celltype)


exp_profiles = data.frame(exp_profiles[['SCT']])

exp_profiles2 <- AverageExpression(ge_so)
exp_profiles2 <- data.frame(exp_profiles2[['SCT']])
exp_profiles$Excitatory <- exp_profiles2$Excitatory
exp_profiles$Inhibitory <- exp_profiles2$Inhibitory


write.table(exp_profiles, '/home/aiden/codes/APA_stuff/post_qual/APA/For_DL_model/celltype_profiles.tsv', sep='\t',
            quote=F)
colnames(exp_profiles)
new_names = c('Oligodendrocytes', 'OPC','AST-PP', 'AST-FB', 'Microglia', 'Endothelial', 'L2-3', 'L4', 'L5-6',
              'L5-6-CC', "Neu-NRGN.II", 'IN-PV', 'IN-SST', 'IN-SV2C', 'IN-VIP', 'Excitatory', 'Inhibitory')
colnames(exp_profiles) <- new_names

write.table(exp_profiles, '/home/aiden/codes/APA_stuff/post_qual/APA/For_DL_model/celltype_profiles.tsv', sep='\t',
            quote=F)





ge_so@active.assay <- 'RNA'

ge_so <- NormalizeData(ge_so, normalization.method = "LogNormalize", scale.factor = 10000, verbose = FALSE)
ge_so <- FindVariableFeatures(ge_so, nfeatures = 2000)
VariableFeatures(ge_so)


## read in the all RBP names
RBPS = read.table('/home/aiden/codes/APA_stuff/post_qual/APA/For_DL_model/RBP_Information.txt', header=T, sep='\t')
RBP_names = RBPS$RBP_Name

length(which(RBP_names %in% rownames(ge_so) ))


features_to_keep = unique(c(RBP_names,VariableFeatures(ge_so)))

length(which(features_to_keep %in% rownames(exp_profiles2$SCT)))

exp_profiles_main_ct <- data.frame(exp_profiles2$SCT)
tst <- data.frame(exp_profiles$SCT, exp_profiles_main_ct$Excitatory, exp_profiles_main_ct$Inhibitory)
new_names = c('Oligodendrocytes', 'OPC','AST-PP', 'AST-FB', 'Microglia', 'Endothelial', 'L2-3', 'L4', 'L5-6',
             'L5-6-CC', "Neu-NRGN.II", 'IN-PV', 'IN-SST', 'IN-SV2C', 'IN-VIP', 'Excitatory', 'Inhibitory')
colnames(tst) = new_names                          
head(tst)

final_exp_profiles <- tst %>% filter(rownames(tst) %in% features_to_keep)
final_exp_profiles <- t(scale(t(final_exp_profiles)))
head(final_exp_profiles)

write.table(final_exp_profiles, '/home/aiden/codes/APA_stuff/post_qual/APA/For_DL_model/celltype_profiles.tsv', sep='\t',
            quote=F)

#summary: celltype profiles are generated by these steps:
#  1- features are SC transformed
#  2- got 2000 valiable features from RNA assay ( after normalization)
#  3- got list of ALL RBPS
#  4- we selected all the variable features and all expressed RBPS
#  5- scaled the featers (for deep learning!)

85 * 16 + 85 * 8 

14 * 85 + 85 * 8 
8 * 85
336 * 1.13 + 96 

14 * 60 + 10 *40 - 40 + 400 


## read in the final annotated ge_So object

library(Seurat)
library(SeuratData)
library(SeuratDisk)

ge_so <- readRDS('/data1/APA/Paul_ALS_Data/ALS_snRNA_final.RDS')
ge_so <- subset(ge_so, subset=chemistry=='V3')


DefaultAssay(ge_so) <- 'RNA'
ge_so@assays[['SCT']] <- NULL
ge_so@assays[['integrated']] <- NULL
SaveH5Seurat(ge_so, filename = "/data1/APA/Paul_ALS_Data/als.h5Seurat")
Convert("/data1/APA/Paul_ALS_Data/als.h5Seurat", dest = "h5ad")



######## lets do this with scVI

library(reticulate)
library(seurat-data)
library(SeuratData)
library(devtools)
devtools::install_github("cellgeni/sceasy")
library(sceasy)

ge_so <- NormalizeData(ge_so, normalization.method = "LogNormalize", scale.factor = 10000)
ge_so <- FindVariableFeatures(ge_so, selection.method = "vst", nfeatures = 5000)

sc <- import("scanpy", convert = FALSE)
scvi <- import("scvi", convert = FALSE)
adata <- convertFormat(ge_so, from="seurat", to="anndata", main_layer="counts", drop_single_values=FALSE)
print(adata) #
